# Generated by Django 5.1.15 on 2026-05-03 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CoachSuggestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "manager_id",
                    models.IntegerField(blank=True, db_index=True, null=True),
                ),
                ("suggestion_date", models.TextField()),
                ("tier", models.TextField()),
                ("suggestion", models.TextField()),
                ("action_page", models.TextField(blank=True, null=True)),
                ("dismissed", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "coach_suggestions",
                "indexes": [
                    models.Index(
                        fields=["manager_id", "suggestion_date"],
                        name="ix_coach_sugg_mgr_date",
                    )
                ],
                "unique_together": {("manager_id", "suggestion_date", "tier")},
            },
        ),
    ]
