from django.contrib import admin
from django.urls import include, path
from django.views.generic import RedirectView

from core import views as core_views

urlpatterns = [
    path("", core_views.hello, name="hello"),
    path("health/", core_views.health, name="health"),
    path("dashboard/", core_views.dashboard, name="dashboard"),
    path("dashboard/panels/overview/", core_views.dashboard_overview, name="dashboard-overview"),
    path("team/", core_views.team_members_list, name="team"),
    path("team/add/", core_views.team_members_add, name="team-add"),
    path("team/<int:member_id>/delete/", core_views.team_members_delete, name="team-delete"),
    path("team/<int:member_id>/restore/", core_views.team_members_restore, name="team-restore"),
    path("events/", core_views.events_upcoming, name="events-upcoming"),
    path("events/schedule/", core_views.events_schedule, name="events-schedule"),
    path("events/<int:event_id>/", core_views.events_detail, name="events-detail"),
    path("events/<int:event_id>/edit/", core_views.events_edit, name="events-edit"),
    path("events/<int:event_id>/complete/", core_views.events_complete, name="events-complete"),
    path("events/<int:event_id>/delete/", core_views.events_delete, name="events-delete"),
    path("events/<int:event_id>/invite/", core_views.events_send_invite, name="events-invite"),
    path("todos/", core_views.todos_list, name="todos"),
    path("todos/add/", core_views.todos_add, name="todos-add"),
    path("todos/<int:todo_id>/complete/", core_views.todos_complete, name="todos-complete"),
    path("todos/<int:todo_id>/uncomplete/", core_views.todos_uncomplete, name="todos-uncomplete"),
    path("todos/<int:todo_id>/delete/", core_views.todos_delete, name="todos-delete"),
    path("journal/", core_views.journal_list, name="journal"),
    path("journal/add/", core_views.journal_add, name="journal-add"),
    path("journal/<int:entry_id>/coaching/", core_views.journal_coaching, name="journal-coaching"),
    path("journal/<int:entry_id>/edit/", core_views.journal_edit, name="journal-edit"),
    path("goals/", core_views.goals_list, name="goals"),
    path("goals/add/", core_views.goals_add, name="goals-add"),
    path("goals/<int:goal_id>/edit/", core_views.goals_edit, name="goals-edit"),
    path("goals/<int:goal_id>/delete/", core_views.goals_delete, name="goals-delete"),
    path("career/", core_views.career_dev, name="career-dev"),
    path("career/skills/add/", core_views.skills_add, name="skills-add"),
    path("career/skills/<int:skill_id>/delete/", core_views.skills_delete, name="skills-delete"),
    path("career/plans/add/", core_views.plans_add, name="plans-add"),
    path("career/plans/<int:plan_id>/status/", core_views.plans_update_status, name="plans-status"),
    path("career/plans/<int:plan_id>/milestones/add/", core_views.milestones_add, name="milestones-add"),
    path("career/milestones/<int:milestone_id>/complete/", core_views.milestones_complete, name="milestones-complete"),
    path("career/convos/add/", core_views.convos_add, name="convos-add"),
    path("career/quarterly-review/", core_views.career_quarterly_review, name="career-quarterly-review"),
    path("delegations/", core_views.delegations_list, name="delegations"),
    path("delegations/add/", core_views.delegations_add, name="delegations-add"),
    path("delegations/<int:delegation_id>/edit/", core_views.delegations_edit, name="delegations-edit"),
    path("delegations/<int:delegation_id>/delete/", core_views.delegations_delete, name="delegations-delete"),
    path("decisions/", core_views.decisions_list, name="decisions"),
    path("decisions/add/", core_views.decisions_add, name="decisions-add"),
    path("decisions/<int:decision_id>/edit/", core_views.decisions_edit, name="decisions-edit"),
    path("decisions/<int:decision_id>/delete/", core_views.decisions_delete, name="decisions-delete"),
    path("meetings/", core_views.one_on_ones_list, name="meetings"),
    path("meetings/new/", core_views.one_on_ones_new, name="meetings-new"),
    path("meetings/add/", core_views.one_on_ones_add, name="meetings-add"),
    path("meetings/<int:session_id>/", core_views.one_on_ones_detail, name="meetings-detail"),
    path("meetings/<int:session_id>/autosave/", core_views.one_on_ones_autosave, name="meetings-autosave"),
    path("meetings/<int:session_id>/complete/", core_views.one_on_ones_complete, name="meetings-complete"),
    path("meetings/<int:session_id>/delete/", core_views.one_on_ones_delete, name="meetings-delete"),
    path("meetings/<int:session_id>/action/", core_views.one_on_ones_add_action, name="meetings-add-action"),
    path("meetings/<int:session_id>/prep-brief/", core_views.one_on_ones_prep_brief, name="meetings-prep-brief"),
    path("meetings/<int:session_id>/prep-brief/generate/", core_views.one_on_ones_prep_brief_generate, name="meetings-prep-brief-generate"),
    path("notes/", core_views.notes_list, name="notes"),
    path("notes/add/", core_views.notes_add, name="notes-add"),
    path("notes/<int:note_id>/delete/", core_views.notes_delete, name="notes-delete"),
    path("feedback/", core_views.feedback_list, name="feedback"),
    path("feedback/add/", core_views.feedback_add, name="feedback-add"),
    path("feedback/draft-sbi/", core_views.feedback_draft_sbi, name="feedback-draft-sbi"),
    path("feedback/<int:feedback_id>/delete/", core_views.feedback_delete, name="feedback-delete"),
    path("search/", core_views.search_page, name="search"),
    path("inbox/", core_views.inbox_list, name="inbox"),
    path("inbox/badge/", core_views.inbox_badge, name="inbox-badge"),
    path("inbox/quick/", core_views.inbox_quick_add, name="inbox-quick"),
    path("inbox/<int:item_id>/triage/", core_views.inbox_triage, name="inbox-triage"),
    path("analytics/", core_views.analytics, name="analytics"),
    path("history/", core_views.history, name="history"),
    path("audit/", core_views.audit_log, name="audit-log"),
    path("resources/", core_views.resources, name="resources"),
    path("settings/", core_views.settings_page, name="settings"),
    path("settings/send-digest/", core_views.settings_send_digest, name="settings-send-digest"),
    path("sentry-debug/", core_views.sentry_debug, name="sentry-debug"),
    # Force Google-only by short-circuiting allauth's default form. The
    # email/password page exists in allauth but we never want users to
    # hit it. Must be registered BEFORE the include() so it wins.
    path(
        "accounts/login/",
        RedirectView.as_view(url="/accounts/google/login/", permanent=False),
    ),
    # Signup is closed at the framework level via ClosedSignupAdapter, but
    # short-circuit the URL too so the form never renders. The bridge
    # middleware (email→Manager) makes open signup an account-takeover risk.
    path(
        "accounts/signup/",
        RedirectView.as_view(url="/accounts/google/login/", permanent=False),
    ),
    path("accounts/", include("allauth.urls")),
    path("admin/", admin.site.urls),
]
