# Generated by Django 5.1.15 on 2026-05-03 20:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LoginAttempt",
            fields=[
                ("username", models.TextField(primary_key=True, serialize=False)),
                ("failed_count", models.IntegerField()),
                ("last_attempt_at", models.DateTimeField()),
                ("locked_until", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "login_attempts",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="SchemaMigration",
            fields=[
                ("id", models.TextField(primary_key=True, serialize=False)),
                ("applied_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "schema_migrations",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Session",
            fields=[
                ("id", models.TextField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                ("last_seen", models.DateTimeField(blank=True, null=True)),
                ("expires_at", models.DateTimeField()),
                ("user_agent_hash", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "sessions",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Decision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "manager_id",
                    models.IntegerField(blank=True, db_index=True, null=True),
                ),
                ("title", models.TextField()),
                ("context", models.TextField(blank=True, null=True)),
                ("alternatives", models.TextField(blank=True, null=True)),
                ("rationale", models.TextField(blank=True, null=True)),
                ("expected_outcome", models.TextField(blank=True, null=True)),
                ("review_date", models.TextField(blank=True, null=True)),
                ("status", models.TextField(blank=True, null=True)),
                ("actual_outcome", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "decisions",
            },
        ),
        migrations.CreateModel(
            name="DevelopmentPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.TextField()),
                ("description", models.TextField(blank=True, null=True)),
                ("target_date", models.TextField(blank=True, null=True)),
                ("status", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
                (
                    "manager_id",
                    models.IntegerField(blank=True, db_index=True, null=True),
                ),
            ],
            options={
                "db_table": "development_plans",
            },
        ),
        migrations.CreateModel(
            name="Manager",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.TextField(unique=True)),
                ("display_name", models.TextField()),
                ("email", models.TextField(blank=True, null=True)),
                ("password_hash", models.TextField()),
                ("work_schedule", models.TextField(blank=True, null=True)),
                ("timezone", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "managers",
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("google_id", models.TextField(unique=True)),
                ("email", models.TextField()),
                ("name", models.TextField(blank=True, null=True)),
                ("picture", models.TextField(blank=True, null=True)),
                ("last_login", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "users",
            },
        ),
        migrations.CreateModel(
            name="Config",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("manager_id", models.IntegerField(db_index=True)),
                ("key", models.TextField()),
                ("value", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "config",
                "unique_together": {("manager_id", "key")},
            },
        ),
        migrations.CreateModel(
            name="JournalEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "manager_id",
                    models.IntegerField(blank=True, db_index=True, null=True),
                ),
                ("entry_date", models.TextField()),
                ("entry_type", models.TextField()),
                ("content", models.TextField(blank=True, null=True)),
                ("mood", models.IntegerField(blank=True, null=True)),
                ("energy", models.IntegerField(blank=True, null=True)),
                ("private_notes", models.TextField(blank=True, null=True)),
                ("tags", models.TextField(blank=True, null=True)),
                ("coaching_response", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "journal_entries",
                "indexes": [
                    models.Index(
                        fields=["manager_id", "entry_date"], name="ix_journal_mgr_date"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Milestone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.TextField()),
                ("target_date", models.TextField(blank=True, null=True)),
                ("completed", models.IntegerField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "manager_id",
                    models.IntegerField(blank=True, db_index=True, null=True),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="core.developmentplan",
                    ),
                ),
            ],
            options={
                "db_table": "milestones",
            },
        ),
        migrations.CreateModel(
            name="SelfAssessment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "manager_id",
                    models.IntegerField(blank=True, db_index=True, null=True),
                ),
                ("week_date", models.TextField()),
                ("dimension", models.TextField()),
                ("score", models.IntegerField()),
                ("created_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "self_assessments",
                "unique_together": {("manager_id", "week_date", "dimension")},
            },
        ),
        migrations.CreateModel(
            name="TeamMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "manager_id",
                    models.IntegerField(blank=True, db_index=True, null=True),
                ),
                ("name", models.TextField()),
                ("email", models.TextField(blank=True, null=True)),
                ("role", models.TextField(blank=True, null=True)),
                ("start_date", models.TextField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "team_members",
                "indexes": [
                    models.Index(fields=["manager_id"], name="ix_team_members_manager")
                ],
            },
        ),
        migrations.CreateModel(
            name="Skill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("skill_name", models.TextField()),
                ("proficiency", models.TextField(blank=True, null=True)),
                ("is_strength", models.IntegerField(blank=True, null=True)),
                ("is_growth_area", models.IntegerField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
                (
                    "manager_id",
                    models.IntegerField(blank=True, db_index=True, null=True),
                ),
                (
                    "team_member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="core.teammember",
                    ),
                ),
            ],
            options={
                "db_table": "skills",
            },
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "manager_id",
                    models.IntegerField(blank=True, db_index=True, null=True),
                ),
                ("title", models.TextField()),
                ("event_type", models.TextField()),
                ("scheduled_date", models.TextField()),
                ("scheduled_time", models.TextField()),
                ("duration_minutes", models.IntegerField(blank=True, null=True)),
                ("location", models.TextField(blank=True, null=True)),
                ("agenda", models.TextField(blank=True, null=True)),
                ("status", models.TextField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, null=True)),
                ("calendar_invite_sent", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
                ("recurrence_rule", models.TextField(blank=True, null=True)),
                ("recurrence_warned_at", models.TextField(blank=True, null=True)),
                (
                    "parent_event",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.event",
                    ),
                ),
                (
                    "team_member",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="core.teammember",
                    ),
                ),
            ],
            options={
                "db_table": "events",
            },
        ),
        migrations.AddField(
            model_name="developmentplan",
            name="team_member",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING, to="core.teammember"
            ),
        ),
        migrations.CreateModel(
            name="Delegation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "manager_id",
                    models.IntegerField(blank=True, db_index=True, null=True),
                ),
                ("task", models.TextField()),
                ("outcome_expected", models.TextField(blank=True, null=True)),
                ("autonomy_level", models.TextField(blank=True, null=True)),
                ("check_in_date", models.TextField(blank=True, null=True)),
                ("status", models.TextField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "team_member",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="core.teammember",
                    ),
                ),
            ],
            options={
                "db_table": "delegations",
            },
        ),
        migrations.CreateModel(
            name="CareerConversation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("conversation_date", models.TextField()),
                ("topic", models.TextField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, null=True)),
                ("next_steps", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                (
                    "manager_id",
                    models.IntegerField(blank=True, db_index=True, null=True),
                ),
                (
                    "team_member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="core.teammember",
                    ),
                ),
            ],
            options={
                "db_table": "career_conversations",
            },
        ),
        migrations.CreateModel(
            name="ActionItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "manager_id",
                    models.IntegerField(blank=True, db_index=True, null=True),
                ),
                ("description", models.TextField()),
                ("assignee", models.TextField(blank=True, null=True)),
                ("due_date", models.TextField(blank=True, null=True)),
                ("status", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "event",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="core.event",
                    ),
                ),
            ],
            options={
                "db_table": "action_items",
                "indexes": [
                    models.Index(
                        fields=["manager_id", "status", "due_date"],
                        name="ix_action_mgr_status_due",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="RunningNote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "manager_id",
                    models.IntegerField(blank=True, db_index=True, null=True),
                ),
                ("note_date", models.TextField()),
                ("content", models.TextField()),
                ("category", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                (
                    "team_member",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="core.teammember",
                    ),
                ),
            ],
            options={
                "db_table": "running_notes",
                "indexes": [
                    models.Index(
                        fields=["team_member", "note_date"],
                        name="ix_running_notes_member_date",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="OneOnOneSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("session_date", models.TextField()),
                ("direct_notes", models.TextField(blank=True, null=True)),
                ("manager_notes", models.TextField(blank=True, null=True)),
                ("followup_notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
                (
                    "event",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.event",
                    ),
                ),
                (
                    "manager",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="core.manager",
                    ),
                ),
                (
                    "team_member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="core.teammember",
                    ),
                ),
            ],
            options={
                "db_table": "one_on_one_sessions",
                "indexes": [
                    models.Index(
                        fields=["manager"], name="ix_one_on_one_sessions_manager"
                    ),
                    models.Index(
                        fields=["team_member", "-session_date"],
                        name="ix_one_on_one_member_date",
                    ),
                ],
                "unique_together": {("manager", "team_member", "session_date")},
            },
        ),
        migrations.CreateModel(
            name="Goal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quarter", models.TextField()),
                ("description", models.TextField()),
                ("key_results", models.TextField(blank=True, null=True)),
                ("status", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
                (
                    "manager_id",
                    models.IntegerField(blank=True, db_index=True, null=True),
                ),
                ("target_date", models.TextField(blank=True, null=True)),
                (
                    "team_member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="core.teammember",
                    ),
                ),
            ],
            options={
                "db_table": "goals",
                "indexes": [
                    models.Index(
                        fields=["manager_id", "target_date"],
                        name="ix_goals_manager_target",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Feedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("feedback_type", models.TextField()),
                ("situation", models.TextField(blank=True, null=True)),
                ("behavior", models.TextField(blank=True, null=True)),
                ("impact", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                (
                    "manager_id",
                    models.IntegerField(blank=True, db_index=True, null=True),
                ),
                (
                    "event",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="core.event",
                    ),
                ),
                (
                    "team_member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="core.teammember",
                    ),
                ),
            ],
            options={
                "db_table": "feedback",
                "indexes": [
                    models.Index(
                        fields=["team_member", "created_at"],
                        name="ix_feedback_member_created",
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(
                fields=["manager_id", "scheduled_date", "status"],
                name="ix_events_manager_date_status",
            ),
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(
                condition=models.Q(("parent_event__isnull", False)),
                fields=["manager_id", "parent_event"],
                name="ix_events_manager_parent",
            ),
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(fields=["parent_event"], name="ix_events_parent"),
        ),
        migrations.AddIndex(
            model_name="delegation",
            index=models.Index(
                fields=["manager_id", "status", "check_in_date"],
                name="ix_deleg_mgr_status_checkin",
            ),
        ),
    ]
