# Generated by Django 5.1.15 on 2026-05-04 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_teammember_deleted_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="actionitem",
            name="due_time",
            field=models.TextField(blank=True, null=True),
        ),
    ]
