# Generated by Django 5.1.15 on 2026-05-10 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_actionitem_due_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manager_id', models.IntegerField(db_index=True)),
                ('action', models.TextField()),
                ('entity_type', models.TextField()),
                ('entity_id', models.IntegerField()),
                ('summary', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'audit_log',
                'indexes': [models.Index(fields=['manager_id', '-created_at'], name='ix_audit_log_mgr_created'), models.Index(fields=['entity_type', 'entity_id'], name='ix_audit_log_entity')],
            },
        ),
    ]
