# Generated by Django 5.1.15 on 2026-05-11 02:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_audit_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='actionitem',
            name='one_on_one_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.oneononesession'),
        ),
        migrations.AddField(
            model_name='oneononesession',
            name='status',
            field=models.TextField(choices=[('draft', 'Draft'), ('completed', 'Completed')], default='draft'),
        ),
    ]
