# Generated by Django 5.1.15 on 2026-05-12 03:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_heal_config_id_pk"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="event",
            name="ix_events_parent",
        ),
    ]
