# Generated by Django 5.1.15 on 2026-05-12 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_drop_redundant_event_parent_index"),
    ]

    operations = [
        migrations.AddField(
            model_name="auditlog",
            name="actor_type",
            field=models.TextField(
                choices=[("user", "User"), ("system", "System")], default="user"
            ),
        ),
    ]
