# Generated by Django 5.1.15 on 2026-07-05 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_oneonone_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='InboxItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manager_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('source', models.TextField(choices=[('quick', 'Quick add'), ('email', 'Email')], default='quick')),
                ('subject', models.TextField(blank=True, null=True)),
                ('body', models.TextField()),
                ('from_address', models.TextField(blank=True, null=True)),
                ('message_id', models.TextField(blank=True, null=True, unique=True)),
                ('received_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.TextField(choices=[('pending', 'Pending'), ('triaged', 'Triaged'), ('dismissed', 'Dismissed'), ('failed', 'Failed')], default='pending')),
                ('triaged_entity_type', models.TextField(blank=True, null=True)),
                ('triaged_entity_id', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'inbox_items',
                'indexes': [models.Index(fields=['manager_id', 'status'], name='ix_inbox_mgr_status')],
            },
        ),
    ]
