# Generated by Django 5.1.15 on 2026-07-07 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_inboxitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='oneononesession',
            name='prep_brief',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='oneononesession',
            name='prep_brief_requested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
