# Generated by Django 5.1.15 on 2026-07-13 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_oneonone_actual_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='actionitem',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
