# Generated by Django 5.1.15 on 2026-07-14 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_actionitem_deleted_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='actionitem',
            name='starred',
            field=models.BooleanField(default=False),
        ),
    ]
